name: 🐛 Bug Report
description: Signaler un bug dans le framework ou l'application blog
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Description du bug
      description: Description claire et concise du problème
      placeholder: Quand je fais X, il se passe Y au lieu de Z
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Faire défiler vers '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: Messages d'erreur
      description: Copiez les messages d'erreur complets
      render: text

  - type: input
    id: php_version
    attributes:
      label: Version PHP
      placeholder: ex. 8.1.2
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Système d'exploitation
      placeholder: ex. Ubuntu 22.04, Windows 11, macOS 13
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Sévérité
      options:
        - Critique (application inutilisable)
        - Haute (fonctionnalité majeure cassée)
        - Moyenne (fonctionnalité mineure affectée)
        - Basse (problème cosmétique)
    validations:
      required: true