name: Issue Automation
on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issues
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.issue.labels.some(label => label.name === 'core')) {
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                assignees: ['VOTRE_USERNAME']
              });
            }