name: Sync Labels

on:
  push:
    branches: [main]
    paths: ['.github/labels.yml']
  workflow_dispatch: # Permet de lancer manuellement

permissions:
  issues: write          # ✅ Permission pour gérer les labels
  contents: read         # ✅ Permission pour lire le repo
  pull-requests: write   # ✅ Permission pour les PR

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    name: Synchroniser les labels
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: true # Supprime les labels non définis